# Generated by Django 5.0.7 on 2024-07-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useregister',
            old_name='Password1',
            new_name='Password',
        ),
    ]
