# Generated by Django 5.0.7 on 2024-07-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_password1_useregister_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useregister',
            old_name='Password',
            new_name='password',
        ),
    ]
