# Generated by Django 5.0.7 on 2024-07-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userregister_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
